// This file is automatically generated by qtc from "home.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/home.qtpl:1
package templates

//line templates/home.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/home.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/home.qtpl:1
func StreamHomeHello(qw422016 *qt422016.Writer, name string) {
	//line templates/home.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html>
  <head>
    <title>CSF Web UI</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/uikit.min.css" />
    <script src="/static/js/uikit.min.js"></script>
    <script src="/static/js/uikit-icons.min.js"></script>
  </head>
  <body class="uk-height-1-1">
    <div class="uk-flex uk-flex-center uk-flex-middle uk-background-secondary uk-height-viewport uk-light">
      <div class="uk-position-bottom-center uk-position-small">
	<span class="uk-text-small uk-text-muted">CSF - Continuous Security Framework</span>
      </div>
      <div class="uk-width-medium">
	<p class="uk-text-legend">
	  Hello, `)
	//line templates/home.qtpl:19
	qw422016.E().S(name)
	//line templates/home.qtpl:19
	qw422016.N().S(`!
	</p>
      </div>
    </div>
</body>
</html>
`)
//line templates/home.qtpl:25
}

//line templates/home.qtpl:25
func WriteHomeHello(qq422016 qtio422016.Writer, name string) {
	//line templates/home.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/home.qtpl:25
	StreamHomeHello(qw422016, name)
	//line templates/home.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line templates/home.qtpl:25
}

//line templates/home.qtpl:25
func HomeHello(name string) string {
	//line templates/home.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/home.qtpl:25
	WriteHomeHello(qb422016, name)
	//line templates/home.qtpl:25
	qs422016 := string(qb422016.B)
	//line templates/home.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/home.qtpl:25
	return qs422016
//line templates/home.qtpl:25
}
